### ISSUE TITLE
provide a summary of RFC 42:C4

### ISSUE THREAD

**Issue by anarcat** [zeromq/rfc#113]
I quite like the process described in the C4 RFC. I think it can be a useful tool to build and improve communities communications and operations.

However, I think the document is too heavy to read. Only because I was _really_ interested in those issues did I decide to bite the bullet and actually read through it. It seems to me it is a rather big barrier to entry to make new contributors read that document as such, especially for people like testers, documenters or graphic artists which may not be so familiar with RFC-style technical documents.

I believe that an Abstract of the document would be a good improvement to the document. It is common for RFCs to have an Abstract and/or Introduction to explain the context and general outline of the process proposed. There is a Goals section, but it doesn't explicitely mention _how_ those goals are accomplished.

Thank you for considering this idea.

**Comment by hintjens** [comment]
Great idea. Would you try writing one? Or at least list the points you
found most important in the RFC, as a new reader.

**Comment by anarcat** [comment]
see #115.

**Comment by anarcat** [comment]
maybe this should have been closed? i am not sure - i still feel the abstract is somewhat incomplete.

**Comment by hintjens** [comment]
I can review this tomorrow but not now, it's midnight here and I have to
sleep.

**Comment by Wambou** [comment]
Hi,
This issue was merged on 23, Sep 2016 through #115, I think it can be closed now.
(Since I am looking at all the issues, why not commenting on this one that is already done)
