### ISSUE TITLE
C4: Administrator and Founder are not documented

### ISSUE THREAD

**Issue by anarcat** [zeromq/rfc#116]
in the "Preliminiaries" section, we define "Contributor" and "Maintainer", but not "Administrator" and "Founder" that are used in the last section.

I am not sure how to define those, but it seems to me those should be more clearly established earlier on.

**Comment by sappo** [comment]
IMO this statement is rather clear:

```
The project founders SHALL act as Administrators to manage the set of project Maintainers.
```
The term founder and administrator are used in the usual fashion. But I'm biased in that regard! If you like to have a more clear explanation please send a PR, with a statement that would have made it easier to you to understand :)

**Comment by anarcat** [comment]
On 2016-09-24 12:59:49, Kevin Sapper wrote:
> IMO this statement is rather clear:
>
> ```
> The project founders SHALL act as Administrators to manage the set of project Maintainers.
> ```
> The term founder and administrator are used in the usual fashion. But I'm biased in that regard! If you like to have a more clear explanation please send a PR, with a statement that would have made it easier to you to understand :)

What is the "usual fashion"?

I don't see that Founders are not defined at all here. What are they?
Are they the first Administrators? The first maintainers? Or just some
people that happened to grant access to people in the beginning?

Administrators are not clearly defined either: what do they do? Do they
*only* determine who is a Maintainer?

I find that the first section states better the distinction (and
overlap) between Maintainers and Contributors. Can a Maintainer be an
Administrator? And vice versa? How about Founders?

This all seems ambiguous. It would seem to me better if this was clearly
defined in the beginning of the document, along with Maintainers and
Contributors.

I'd gladly make a PR for that, but I first need to get clarification on
the intended definition and purpose for Founders and Admins.. :)

Thanks!

A.

-- 
Le matraquage publicitaire est une forme moderne et supérieure de la
propagande.
                        - Henri Gobard

**Comment by hintjens** [comment]
Founder creates the project and/or is moral owner in some sense.
Administrator is maintainer with admin rights, ie to promote or eject
maintainers.
