### ISSUE TITLE
Problem: Links are broken

### ISSUE THREAD

**Issue by sappo** [zeromq/rfc#120]
Currently all link in this format are broken: [http://rfc.zeromq.org/spec:42](http://rfc.zeromq.org/spec:42)
The default gitbook links still work: [http://rfc.zeromq.org/42](http://rfc.zeromq.org/42 )

@yrashk you took care of this if I'm not mistaken. Could you please have a look at what's going on. Thanks.

**Comment by yrashk** [comment]
@sappo ouch! taking a look

**Comment by yrashk** [comment]
The links seem to work just fine when served locally. I am wondering if gitbook.com has changed anything.

**Comment by yrashk** [comment]
I just opened a ticket with gitbook, as I am quite limited in terms of being able to see what's happening on their side.

**Comment by sappo** [comment]
Thanks!

**Comment by yrashk** [comment]
The guys at gitbook.com have fixed it. Not sure what was the issue, but it seems to work now! Thanks @jpreynat!

**Comment by bluca** [comment]
Thanks!
