### ISSUE TITLE
License confusion (GPL vs. MPL [.... And others])

### ISSUE THREAD

**Issue by ClosetMonkey** [zeromq/rfc#133]
As a written work, ZMTP and other RFCs seem to be licensed under GPL, yet the reference implementation of ZMTP (libzmtp) is licensed under the slightly less restrictive MPL. This creates confusion. Namely, if one makes a modified version of ZMTP will it be required to release/share the changes in the form of a GPL covered upgrade to the ZMTP RFC or will the code itself be required to be licensed under GPL? This may seem like a silly issue, but in order to fully respect your works (and stay in line legally...), this needs to be clearer.

**Comment by ClosetMonkey** [comment]
As it stands, one can modify libzmtp and will only have to license it as MPL which seems to contradict what's stated in the last points in the Goals section of RFC 23 (https://github.com/zeromq/rfc/blob/master/23/README.md#goals)

**Comment by ClosetMonkey** [comment]
Also, a quick browse through bindings etc brings in even less restrictive licenses including MIT even though they are either linking to the GPLed libzmq or are stand-alone implementations of the GPLed RFCs

**Comment by bluca** [comment]
Copyright covers the specific text, not any implementation of the abstract idea (that would be patents). So modifications to the RFC texts themselves and any derivative work have to be released under the same license, which is GPL3.

Implementations like libzmtp are licensed under the MPL2, which is share-alike just like the the GPL: you have to release any modifications you make to the library. So the goals are still respected.

libzmq is not GPL, it's LGPL, which means you can link to it (statically or dynamically) without changing the license of the program. The binding's license does not change the license of libzmq.

Full implementations are either LGPL3 (netmq) or MPL2 (libzmtp, jeromq, chumak). Can't think of any that isn't, but I might be forgetting one.

If someone were to make a clean room implementation using only reverse engineering, without reading the RFCs or the source code of the implementations, they could choose the license of the software and of the published protocol as they wish. That's how copyright works, only patents could stop that - and there aren't any, by choice.

**Comment by ClosetMonkey** [comment]
Thank you, that pretty much nailed it.
