### ISSUE TITLE
37/ZMTP 3.1 still in draft

### ISSUE THREAD

**Issue by Wambou** [zeromq/rfc#160]
Hi,

It seems that RFC 37/ZMTP defining the 3.1 version of the protocol is implemented in libzmq, should it be moved to Stable now ?

Maybe some other RFC are in use but not moved, like 42/C4.
Also, some deprecated RFC could be moved the same way.

Sorry, I am making lots of movement today :smile:

**Comment by bluca** [comment]
it's not fully implemented, metadata is missing

**Comment by Wambou** [comment]
OK, this was not easily visible, sorry for bothering...
