### ISSUE TITLE
Problem: Inaccurate contribution instructions

### ISSUE THREAD

**Issue by justusranvier** [zeromq/rfc#197]
The readme file for this repository claims the contribution process is per C4, however this is plainly not the case.

Pull request #196 was rejected despite C4 2.4.14 "Maintainers SHALL NOT make value judgments on correct patches."

In order to avoid misunderstandings it would be helpful to document the actual contribution rules so all potential contributors know what to expect. 

Advertising a standard which is not actually followed helps no one.

**Comment by bluca** [comment]
Endorsing planet-burning scams is not a "correct patch"
