### ISSUE TITLE
Problem: Public APIs only "should" be publicly documented, but for my project, I need this to be a requirement.

### ISSUE THREAD

**Issue by sam-falvo** [zeromq/rfc#70]
Problem: Kestrel project (independent of 0MQ; see http://kestrelcomputer.github.io/kestrel) demands that public APIs and other specifications be published in some form of documentation.  C4 currently doesn't enforce this; instead, it only says that public standards "SHOULD" be documented.  The Kestrel project would like to adopt the C4 process going forward, but would like to tailor this one feature, above anything else, to reflect the Kestrel Project values.

I started by forking the C4.1 process and tailoring it to the Kestrel project.  After some discussions with Pieter Hintjens, we decided to contribute some of my tweaks back to the original RFC instead.  Thus, I'm opening this issue as a means of detailing what the problem is (for me), and possibly to solicit feedback on the PR I will subsequently submit, in a way that is strictly compatible with the current C4.1 process.

**Comment by hintjens** [comment]
Problem: should is too weak for public APIs

Solution: use MUST

:) Send a PR, I'll merge it.

**Comment by sam-falvo** [comment]
Addressed by #71
