### ISSUE TITLE
Problem: recommended pattern for list iteration is broken

### ISSUE THREAD

**Issue by sappo** [zeromq/rfc#73]
In RFC/21 CLASS the recommended pattern for list iteration is only `<type>` which cannot be valid. An commonly used approach in czmq is:

```c
myp_mymod_t *mymod = myp_mymod_first (mymod);
while (mymod) {
    //  Do something
    mymod = myp_mymod_next (mymod);
}
```

**Comment by hintjens** [comment]
Good catch. Fixed it, thanks.
