### ISSUE TITLE
37/ZMTP marked as 'raw' on the wiki

### ISSUE THREAD

**Issue by elliotcm** [zeromq/rfc#94]
37/ZMTP is considered "draft" within the context of the specs and index, however [the wiki page](http://rfc.zeromq.org/spec:37) lists it as "raw".

I didn't want to attempt the change myself as I don't know which implementation exists which moved it out of raw and into draft.

**Comment by hintjens** [comment]
I've marked it as draft. We implement part of it (ping, pong) in libzmtp.
We may remove subscribe/cancel from the draft text.

**Comment by elliotcm** [comment]
👍
